### ISSUE TITLE
Error with parcel/transformer-js

### ISSUE THREAD

**Issue by TheManFromEarth1** [gnomical/solid-theme-provider#1]
Thanks for the library.

I seem to get this error with parcel. Will see what I can find

`🚨 @parcel/transformer-js: Expected ',', got 'xmlns'

[../node_modules/solid-theme-provider/dist/solid-theme-provider.jsx:71:33](http://localhost:1234/__parcel_launch_editor?file=%2Fhome%2Fjet%2Fwww%2Fdevilbox%2Fdata%2Fwww%2Fhookito-nextjs%2Fhtdocs%2Fhookito-extension-solidjs%2Fnode_modules%2Fsolid-theme-provider%2Fdist%2Fsolid-theme-provider.jsx%3A71%3A33)
  70 | 
> 71 | <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25.9 25.9">
>    |      ^^^^^
  72 |     <path d="M7.95,24.88c-1.56-.68-2.94-1.61-4.13-2.81s-2.13-2.57-2.81-4.
  73 |   </svg>);`

Versions:
 "solid-js": "^1.4.8",
 "solid-theme-provider": "^0.5.0",

**Comment by gnomical** [comment]
Thanks for the info. I just released a new version but a fix for this was not included in the update. 

I don't use parcel in any of my build pipelines. If you can link me to a project that is experiencing this issue I may be able to look into it.

**Comment by gnomical** [comment]
After a bit of research it appears that parcel has regular issues of this type. It seems to not handle jsx and typescript very well (https://github.com/parcel-bundler/parcel/issues/6176) and it has consistency issues loading .babelrc (https://github.com/solidjs/solid/discussions/884).

I would recommend switching to `vite`, the official way to build solidjs projects. (https://github.com/solidjs/templates)

**Comment by gnomical** [comment]
Let me know if switching build tools is satisfactory. If so, I'd like to close this issue.
