### ISSUE TITLE
Drop down not dropping down.

### ISSUE THREAD

**Issue by thecodefool** [gnomical/solid-theme-provider#2]
Awesome Project! thanks for the cool utility!

I have copied your config file over to my project and cannot seem to get the drop-down to drop down.

Happy to upload a sample if you need it.

Thanks again!

**Comment by gnomical** [comment]
Should be good to go, let me know if you have any other issues!

**Comment by thecodefool** [comment]
Thanks for the quick response.  Looks good thanks again!!
